import pygame
from math import *

pygame.init()

TIMESCALE = 0.05

RANDOM_SEED_RANGE = 8192

WHITE = (255,255,255)
BLACK = (0,0,0)
RED = (255,0,0)
GREEN = (0,255,0)
BLUE = (0,0,255)
PURPLE = (255,0,255)
YELLOW = (255, 255, 0)
DEBUG_COLOUR = PURPLE
DEBUG_COLOUR_2 = YELLOW

BACKGROUND_COLOUR = BLACK

DEFAULT_FONT = pygame.font.Font('freesansbold.ttf', 32)
MENU_FONT = pygame.font.Font('freesansbold.ttf', 64)
SCORE_FONT = pygame.font.Font('freesansbold.ttf', 32)
DEBUG_FONT = pygame.font.Font('freesansbold.ttf', 12)

BULLET_LENGTH = 15
BULLET_WIDTH = 3
BULLET_CHECK_DISTANCE = (64*1)**2 #squared distance
BULLET_CHUNK_SIZE = 12

PLAYER_SPEED = 0.6
PLAYER_HORIZONTAL_SPEED = 300 * PLAYER_SPEED
PLAYER_FORWARD_SPEED = 200 * PLAYER_SPEED
PLAYER_BACKWARD_SPEED = 400 * PLAYER_SPEED
PLAYER_HEALTH = 1

ENEMY_X_PARTITIONS = 12
ENEMY_Y_PARTITIONS = 12
PARTITION_THREADS = 4
ENEMY_SPAWN_CHANCE = 10
ENEMY_FOV = 90
ENEMY_SIGHT_DIST = 10**2
ENEMY_ACCELERATION = 0.3
ENEMY_MAX_SPEED = 1
ENEMY_FRICTION = 0.95
ENEMY_REPULSION = 0.2
ENEMY_ALIGNMENT_STRENGTH = 0.2
ENEMY_CMASS_WEIGHTING = 0.5
ENEMY_COLOUR = WHITE
ENEMY_RANDOMNESS = radians(45)
ENEMY_TARGET_WEIGHTING = 0.2

PLAYER_BULLET_SPEED = 250
PLAYER_BULLET_SIZE = 1.5 #radius
PLAYER_BULLET_EXPLOSION_SIZE = 40
PLAYER_BULLET_HEALTH = 1
PLAYER_BULLET_HEALTH_CHARGED = 100
PLAYER_BULLET_CHARGE_TIME = 1.3
PLAYER_BULLET_COLOUR = (255, 191, 41)
PLAYER_BULLET_COLOUR_CHARGED = (100, 100, 255)

ENEMY_BULLET_SPEED = 90
ENEMY_BULLET_SIZE = 1.5
ENEMY_BULLET_HEALTH = 30
ENEMY_BULLET_COLOUR = (255, 206, 92)

ASTEROID_SPAWN_CHANCE = 100 #out of 6000
ASTEROID_COLOUR = (199, 199, 199)
ASTEROID_MIN_SPEED = 15
ASTEROID_MAX_SPEED = 60
ASTEROID_DURABILITY = 1
ASTEROID_CHUNK_SIZE = 3
ASTEROID_SHAPE_LARGE = (256,256)
ASTEROID_SHAPE_MEDIUM = (128,128)
ASTEROID_SHAPE_SMALL = (64,64)
ASTEROID_RESOLUTION = (2,2)
ASTEROID_OCTAVES = 5
ASTEROID_NOISE_THRESHOLD = 0.01
ASTEROID_NOISE_MULTIPLIER = -0.05
NUM_LARGE_ASTEROIDS = 15
NUM_MEDIUM_ASTEROIDS = 15
NUM_SMALL_ASTEROIDS = 60

#ENEMY_SPAWN_CHANCE = 10
#ENEMY_SPEED = 200
#ENEMY_MAX_SPEED = 100
#ENEMY_HEALTH = 1
#ENEMY_HEIGHT_THRESHOLD = 500
#ENEMY_HEIGHT_WEIGHTING = 0#.0005
#ENEMY_REPULSION = 10
#ENEMY_FOV = radians(135)
#ENEMY_DIRECTION_ATTRACTION = 0.1
#ENEMY_OBSTACLE_REPULSION = 0#1.2#0.02
#ENEMY_PLAYER_ATTRACTION = 50
#ENEMY_MASS_ATTRACTION = 10
#ENEMY_INTERACTION_DISTANCE = 64**2
#ENEMY_DIRECTION_VARIATION = 10